-- Seed di prova per Charon. Gira automaticamente all'avvio del container
-- (l'immagine postgres esegue i .sql in /docker-entrypoint-initdb.d).
--
-- Crea lo schema nella sorgente (charon_src) e lo DUPLICA vuoto nella
-- destinazione data-only (charon_dst), lasciando charon_full completamente vuoto.

-- ---- Schema + dati nella sorgente ------------------------------------------
CREATE TABLE customers (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  text    NOT NULL,
    email text
);

CREATE TABLE orders (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id integer NOT NULL,
    total       numeric(10,2) NOT NULL
);

INSERT INTO customers (name, email) VALUES
    ('Alice Rossi',   'alice.rossi@example.com'),
    ('Bruno Bianchi', 'bruno.bianchi@example.com'),
    ('Carla Verdi',   'carla.verdi@example.com');

INSERT INTO orders (customer_id, total) VALUES
    (1, 19.90),
    (1, 5.00),
    (2, 120.00),
    (3, 0.99);

-- ---- Database aggiuntivi ----------------------------------------------------
CREATE DATABASE charon_dst;
CREATE DATABASE charon_full;

-- Nella destinazione data-only ricreiamo SOLO lo schema (nessun dato): è lo
-- scenario "schema gestito da migration" descritto nella documentazione.
\connect charon_dst
CREATE TABLE customers (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  text    NOT NULL,
    email text
);
CREATE TABLE orders (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id integer NOT NULL,
    total       numeric(10,2) NOT NULL
);
