-- Schema di prova per lo schema applicativo JFORM_DEV (creato da APP_USER).
-- gvenzl/oracle-free esegue questo file come APP_USER dentro FREEPDB1.
--
-- Tabelle con colonna ID identity (per dimostrare il RIALLINEO delle sequenze
-- dopo il load, come richiesto dalla documentazione) e senza dati: i dati
-- arrivano da `charon oracle-load` (pacchetto SQL*Loader) o da un clone.

CREATE TABLE "CUSTOMERS" (
  "ID"    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "NAME"  VARCHAR2(100) NOT NULL,
  "EMAIL" VARCHAR2(200)
);

CREATE TABLE "ORDERS" (
  "ID"          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CUSTOMER_ID" NUMBER NOT NULL,
  "TOTAL"       NUMBER(10,2) NOT NULL
);
