OPTIONS (ERRORS=50)
LOAD DATA
CHARACTERSET UTF8
INFILE 'CUSTOMERS.ldr' "str '{EOL}'"
APPEND
INTO TABLE "CUSTOMERS"
FIELDS TERMINATED BY '|'
OPTIONALLY ENCLOSED BY '#' AND '#'
TRAILING NULLCOLS (
  "ID" ,
  "NAME" CHAR(100),
  "EMAIL" CHAR(200)
)
