OPTIONS (ERRORS=50)
LOAD DATA
CHARACTERSET UTF8
INFILE 'ORDERS.ldr' "str '{EOL}'"
APPEND
INTO TABLE "ORDERS"
FIELDS TERMINATED BY '|'
OPTIONALLY ENCLOSED BY '#' AND '#'
TRAILING NULLCOLS (
  "ID" ,
  "CUSTOMER_ID" ,
  "TOTAL"
)
